const cursorDarkMidnight = {
  name: "cursor-dark-midnight",
  type: "dark" as const,
  colors: {
    "editor.background": "#1e2127",
    "editor.foreground": "#7b88a1",
    "editorLineNumber.foreground": "#4c566a",
    "editorLineNumber.activeForeground": "#687692",
    "editorGutter.background": "#1e2127",
    "editorGutter.addedBackground": "#a3be8c",
    "editorGutter.deletedBackground": "#bf616a",
    "editorGutter.modifiedBackground": "#ebcb8b",
    "diffEditor.insertedTextBackground": "#a3be8c22",
    "diffEditor.removedTextBackground": "#bf616a22",
  },
  tokenColors: [
    { scope: "emphasis", settings: { fontStyle: "italic" } },
    { scope: "strong", settings: { fontStyle: "bold" } },
    { scope: "comment", settings: { foreground: "#8597BCA6", fontStyle: "italic" } },
    { scope: "constant.character", settings: { foreground: "#EBCB8B" } },
    { scope: "constant.character.escape", settings: { foreground: "#EBCB8B" } },
    { scope: "constant.language", settings: { foreground: "#81A1C1" } },
    { scope: "constant.numeric", settings: { foreground: "#B48EAD" } },
    { scope: "constant.language.boolean.true", settings: { foreground: "#B48EAD" } },
    { scope: "constant.language.boolean.false", settings: { foreground: "#B48EAD" } },
    { scope: "constant.language.undefined", settings: { foreground: "#7D7C9B" } },
    { scope: "constant.language.null", settings: { foreground: "#7D7C9B" } },
    { scope: "constant.regexp", settings: { foreground: "#EBCB8B" } },
    { scope: ["entity.name.class", "entity.name.type.class"], settings: { foreground: "#8FBCBB" } },
    { scope: "entity.name.function", settings: { foreground: "#88C0D0" } },
    { scope: "entity.name.tag", settings: { foreground: "#81A1C1" } },
    { scope: "entity.other.attribute-name", settings: { foreground: "#8FBCBB", fontStyle: "italic" } },
    { scope: "entity.other.inherited-class", settings: { foreground: "#8FBCBB", fontStyle: "bold" } },
    { scope: "invalid.deprecated", settings: { foreground: "#EBCB8B" } },
    { scope: "invalid.illegal", settings: { foreground: "#BF616A" } },
    { scope: "keyword", settings: { foreground: "#81A1C1" } },
    { scope: "keyword.operator", settings: { foreground: "#81A1C1" } },
    { scope: "keyword.other.new", settings: { foreground: "#81A1C1" } },
    { scope: "markup.bold", settings: { fontStyle: "bold" } },
    { scope: "markup.changed", settings: { foreground: "#EBCB8B" } },
    { scope: ["markup.deleted", "punctuation.definition.deleted"], settings: { foreground: "#BF616A" } },
    { scope: ["markup.inserted"], settings: { foreground: "#A3BE8C" } },
    { scope: "meta.preprocessor", settings: { foreground: "#5E81AC" } },
    { scope: "punctuation", settings: { foreground: "#ECEFF4" } },
    { scope: ["punctuation.definition.method-parameters", "punctuation.definition.function-parameters", "punctuation.definition.parameters"], settings: { foreground: "#ECEFF4" } },
    { scope: "punctuation.definition.tag", settings: { foreground: "#81A1C1" } },
    { scope: ["punctuation.definition.comment", "punctuation.end.definition.comment", "punctuation.start.definition.comment"], settings: { foreground: "#4C566A" } },
    { scope: ["punctuation.definition.inserted"], settings: { foreground: "#A3BE8C" } },
    { scope: ["punctuation.definition.deleted"], settings: { foreground: "#BF616A" } },
    { scope: "punctuation.section", settings: { foreground: "#ECEFF4" } },
    { scope: ["punctuation.section.embedded.begin", "punctuation.section.embedded.end"], settings: { foreground: "#81A1C1" } },
    { scope: "punctuation.terminator", settings: { foreground: "#81A1C1" } },
    { scope: "punctuation.definition.variable", settings: { foreground: "#81A1C1" } },
    { scope: "storage", settings: { foreground: "#81A1C1" } },
    { scope: "string", settings: { foreground: "#A3BE8C" } },
    { scope: "string.regexp", settings: { foreground: "#EBCB8B" } },
    { scope: "support.class", settings: { foreground: "#8FBCBB" } },
    { scope: "support.constant", settings: { foreground: "#81A1C1" } },
    { scope: "support.function", settings: { foreground: "#88C0D0" } },
    { scope: "support.function.construct", settings: { foreground: "#81A1C1" } },
    { scope: "support.type", settings: { foreground: "#8FBCBB" } },
    { scope: "support.type.exception", settings: { foreground: "#8FBCBB" } },
    { scope: "token.debug-token", settings: { foreground: "#B48EAD" } },
    { scope: "token.error-token", settings: { foreground: "#BF616A" } },
    { scope: "token.info-token", settings: { foreground: "#88C0D0" } },
    { scope: "token.warn-token", settings: { foreground: "#EBCB8B" } },
    { scope: "variable.other", settings: { foreground: "#D8DEE9" } },
    { scope: "variable.language", settings: { foreground: "#81A1C1" } },
    { scope: "variable.parameter", settings: { foreground: "#D8DEE9" } },
    { scope: "source.js meta.object-literal.key", settings: { foreground: "#88C0D0" } },
    { scope: "source.js storage.type.class.jsdoc", settings: { foreground: "#8FBCBB" } },
    { scope: "source.js string.template punctuation.definition.template-expression", settings: { foreground: "#5E81AC" } },
    { scope: ["source.ts support.class", "source.ts support.type", "source.ts entity.name.type", "source.ts entity.name.class", "source.tsx support.class", "source.tsx support.type", "source.tsx entity.name.type", "source.tsx entity.name.class"], settings: { foreground: "#8FBCBB" } },
    { scope: ["source.ts meta.object-literal.key", "source.tsx meta.object-literal.key"], settings: { foreground: "#D8DEE9" } },
    { scope: ["source.ts meta.object-literal.key entity.name.function", "source.tsx meta.object-literal.key entity.name.function"], settings: { foreground: "#88C0D0" } },
    { scope: ["source.ts punctuation.decorator", "source.tsx punctuation.decorator"], settings: { foreground: "#D08770" } },
    { scope: "source.python support.type", settings: { foreground: "#88C0D0" } },
    { scope: "source.python entity.name.function.decorator", settings: { foreground: "#D08770" } },
    { scope: "source.css support.type.property-name", settings: { foreground: "#D8DEE9" } },
    { scope: "source.css meta.property-value", settings: { foreground: "#88C0D0" } },
    { scope: "source.yaml entity.name.tag", settings: { foreground: "#8FBCBB" } },
    { scope: "markup.heading", settings: { foreground: "#88C0D0" } },
    { scope: ["text.html.markdown markup.inline.raw"], settings: { foreground: "#8FBCBB" } },
    { scope: "text.html.markdown beginning.punctuation.definition.list", settings: { foreground: "#81A1C1" } },
    { scope: "source.rust entity.name.type", settings: { foreground: "#8FBCBB" } },
    { scope: "source.rust entity.name.function", settings: { foreground: "#88C0D0" } },
    { scope: "source.go constant.other.placeholder.go", settings: { foreground: "#EBCB8B" } },
  ],
};

export default cursorDarkMidnight;
